name: Run Python Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes (UTC)
  workflow_dispatch:        # allows manual run

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      - name: Run Python script
        run: python src/main.py
